# Node ID
node_id:          0

# Rate to publish control signal
ctrl_rate:        20

# Feedback topic
odom_topic:       "/airsim_node/drone_0/odom_global"


# Points to stop as the drone sweeps the surface

# XZ plane 
# setpoints:
#   [ 0,  0,  2,
#     0,  0,  9,
#    -17, 0,  9,
#    -17, 0,  7.5,
#    -2,  0,  7.5,
#    -2,  0,  6,
#    -17, 0,  6,
#    -17, 0,  4.5,
#    -2,  0,  4.5,
#    -2,  0,  3,
#    -17, 0,  3,
#    -17, 0,  1.5,
#    -2,  0,  1.5,
#    -2,  0, -10 ]

# Interwoven straight line
setpoints:
  [ 0,    0,    2,
    0,    0,    9,

  -15.0,  0,    9,
   -15.0, 2.5,  9,
   -2.5,  2.5,  9,
   -2.5,  5.0,  9,
   -15.0, 5.0,  9,
   -15.0, 7.5,  9,
   -2.5,  7.5,  9,
   
   -2.5,  7.5,  7.5,
   -2.5,  0.0,  7.5,
   -5.0,  0.0,  7.5,
   -5.0,  7.5,  7.5,
   -7.5,  7.5,  7.5,
   -7.5,  0.0,  7.5,
   -10.0, 0.0,  7.5,
   -10.0, 7.5,  7.5,
   -12.5, 7.5,  7.5,
   -12.5, 0.0,  7.5,
   -15.0, 0.0,  7.5,
   -15.0, 7.5,  7.5,
    
   -15.0, 7.5,  6.0,
   -2.5,  7.5,  6.0,
   -2.5,  5.0,  6.0,
   -15.0, 5.0,  6.0,
   -15.0, 2.5,  6.0,
   -2.5,  2.5,  6.0,
   -2.5,  0.0,  6.0,
   -15.0, 0.0,  6.0,
   
   -15.0, 0.0,  4.5,
   -15.0, 7.5,  4.5,
   -12.5, 7.5,  4.5,
   -12.5, 0.0,  4.5,
   -10.0, 0.0,  4.5,
   -10.0, 7.5,  4.5,
   -7.5,  7.5,  4.5,
   -7.5,  0.0,  4.5,
   -5.0,  0.0,  4.5,
   -5.0,  7.5,  4.5,
   -2.5,  7.5,  4.5,
   -2.5,  0.0,  4.5,
    
   -2.5,  0.0, -10.0]

# velocity from stops to stops, in m/s
sweep_velocity:   1.0


# Tolerance to determine if the drone has reached the setpoint
reach_tolerance:  0.1
